### ISSUE TITLE
“LoginWebView. CoreWebView2. NewWindowRequested + = CoreWebView2_NewWindowRequested;" This line of code will automatically jump out, can not get the code and token

### ISSUE THREAD

**Issue by wuxiao-ling197** [casdoor/casdoor-dotnet-winform-example#7]
Hello, when I executed this example, I modified the casdoor information configured for my machine. But the login interface implementation to    **“LoginWebView. CoreWebView2. NewWindowRequested + = CoreWebView2_NewWindowRequested;"**  This line of code will automatically jump out, can not get the code and token, can you tell me what changes need to be made

**Comment by hsluoyz** [comment]
@wuxiao-ling197 I don't know what you mean. Provide:

1. The code and config changes
2. Demo video to show your error

**Comment by wuxiao-ling197** [comment]
![01](https://github.com/casdoor/casdoor-dotnet-winform-example/assets/77096395/cfc4f847-b8cc-4a37-b2c3-d56083a7aebd)
![02](https://github.com/casdoor/casdoor-dotnet-winform-example/assets/77096395/072dd073-8d99-4897-b47b-dac256beada8)
![03](https://github.com/casdoor/casdoor-dotnet-winform-example/assets/77096395/7cde6330-8ab4-4588-8755-771a74be620e)

@hsluoyz hello,this is what my error.I only changed the CasdorOptions params and then just run this ConsoleApp program,is these enough to describe my error?but if I run it in MVCApp it was success,Thank you ver much!

**Comment by hsluoyz** [comment]
@lywedo

**Comment by hsluoyz** [comment]
@wuxiao-ling197 this repo doesn't have any code related to `ConsoleApp` or 

![image](https://github.com/casdoor/casdoor-dotnet-winform-example/assets/3787410/7dbf3c03-5a2e-4e3a-a314-887992e2d297)

You found the wrong repo.

**Comment by wuxiao-ling197** [comment]
> @wuxiao-ling197 this repo doesn't have any code related to `ConsoleApp` or
> 
> ![image](https://private-user-images.githubusercontent.com/3787410/286606820-7dbf3c03-5a2e-4e3a-a314-887992e2d297.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjEzMDcsIm5iZiI6MTcwMTMyMTAwNywicGF0aCI6Ii8zNzg3NDEwLzI4NjYwNjgyMC03ZGJmM2MwMy01YTJlLTRlM2EtYTMxNC04ODc5OTJlMmQyOTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDUxMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVmNjdmMjcxNzlmNzkwM2FlZDMwOWI2NDI1ZWEyNzJjNDg2NDlkNDYyYzc3NTk5MDFkM2IwOGUxYWIwNWJhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0n45XQGjLNw4xZcVL_iHSSnXeVk_Zt4eQaxocXJqHAw)
> 
> You found the wrong repo.

oh sorry , it was from https://github.com/casdoor/casdoor-dotnet-sdk ,I put it in wrong place.

**Comment by hsluoyz** [comment]
Moved to: https://github.com/casdoor/casdoor-dotnet-sdk/issues/91
